### ISSUE TITLE
Beta SteamOS Branch issue

### ISSUE THREAD

**Issue by moraroy** [moraroy/NonSteamLaunchersDecky#12]
@elpendor

**Comment by elpendor** [comment]
@moraroy Testing your latest version, GOG install is still failing. 

Issue seems to be when running GalaxySetup.exe with that particular latest GE-Proton (I think), because when I recreate the script steps with the latest umu-launcher, seems to work fine.

Other launchers seems to work fine.

**Comment by moraroy** [comment]
@elpendor i was able to find a fix brother ill be updating soon

**Comment by moraroy** [comment]
@elpendor just sent the fix in bro, i tested on beta and gog was able to install, hopefully this wont mess up any other launchers

**Comment by moraroy** [comment]
@elpendor the fixes should be live now! Let me know!
