### ISSUE TITLE
How to install Decky Loader Plugin

### ISSUE THREAD

**Issue by W13N3N** [moraroy/NonSteamLaunchersDecky#2]
Hi,

How to install the decky loader plugin? And can i install this when i already installed NSL in Desktop mode?

Thanks for your awesome work!!

**Comment by moraroy** [comment]
@W13N3N yes and yes. Go to Game Mode and open up the decky plugin and  go to settings change store to "Testing"

**Comment by W13N3N** [comment]
@moraroy thanks for your quick reply!! Will give it a try when i'm at home.

**Comment by xlapinvx** [comment]
looking forward to this feature as a public release!! thanks!
Hope uninstalled games from the nonsteam stores will be visible from library menus

**Comment by moraroy** [comment]
@xlapinvx hmmmm it's possible... I'm not very good with ui things though sorry the plugins looks terrible! Lol

**Comment by W13N3N** [comment]
@moraroy the plugin works great!! Very easy to add new launchers, or Twitch, Youtube etc. 🦾

I just read your not that good with UI things ;-) (although it looks pretty straight forward) but it would be nice if you could see which launchers are already installed, and maybe (nice to have) to uninstall them aswell. (although this is still easy/possible withing desktop mode)

Side question; should the game scanner also delete games from your library when deleted? I've tested this but it didn't work.

Keep up the good work!!

**Comment by W13N3N** [comment]
@moraroy sounds great!! Take your time!! And if i can help with testing please let me know!

**Comment by kzkzkzkzkzk** [comment]
Sorry, I'm Japanese and the translation is a bit difficult, so I'll ask a question. I'm currently using chimeraOS on rogally, I installed the loader and introduced the plugin, how do I add epic and YouTube to the library? Even if I check and press install, it doesn't get added to the library.

**Comment by moraroy** [comment]
@kzkzkzkzkzk this has been fixed in the latest revisions.
