### ISSUE TITLE
Getting double boot with this plugin installed

### ISSUE THREAD

**Issue by 2ndHouse** [moraroy/NonSteamLaunchersDecky#4]
Great app and plugin! I used it to install a Luna launcher (which is working great). After installing though I was getting a weird issue where my Deck would boot a second time after the initial boot. Not a big problem, more of an annoyance. The problem has gone away after uninstalling the plugin.

It's hard to say what the problem was exactly. Best guess would be that the scanner function was perhaps a little buggy when the Deck was booting up. Anyway, thought I would mention this in case someone else has this problem. Will try again after the plugin is out of the testing phase.

**Comment by moraroy** [comment]
@2ndHouse I'm currently waiting for version 1.0 to be approved. This bug will no longer be there.

**Comment by moraroy** [comment]
@2ndHouse https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527

**Comment by 2ndHouse** [comment]
@moraroy Good to know! I'll go ahead and close this
