### ISSUE TITLE
Adding games with DLC in GOG Galaxy will add shortcuts for each DLC as well.

### ISSUE THREAD

**Issue by paladin181** [moraroy/NonSteamLaunchersDecky#5]
Tested with Asterigos: Curse of the Stars. 
Tested with The Witcher 3: Wild Hunt (original release)
Installed on GOG Galaxy and ran manual scan. Got shortcuts for the games and each individual DLC added to Steam.

Decky Version 2.12.0, Plugin version:1.00.0-91b52e1

**Comment by moraroy** [comment]
Cool thanks man for some reason on reddit I thought you were doing a pull request! My bad otherwise I would have taken care of it myself. But these issues are good to keep track. Thank you. Will do my best to get them fixed asap!

**Comment by moraroy** [comment]
@paladin181 fixed in both! But the plugin won't have this fix yet until it's approved (don't know when)
