### ISSUE TITLE
Unistall launcher from decky

### ISSUE THREAD

**Issue by kafkaus** [moraroy/NonSteamLaunchersDecky#7]
Hi, first of all thank you for your work, it's an incredible resource for steam deck owners. I have a question that maybe has a simple answer but I can't find it. How do you uninstall a laucher installed by the decky loader plugin?

**Comment by moraroy** [comment]
@kafkaus havn't added those buttons yet! For now Start Fresh is the only option! That will wipe NSL though :( you could use the desktop version to uninstall though!

**Comment by kafkaus** [comment]
Are you telling me that I can install the launchers from the decky plugin and then  them from the desktop version, or do I have to install and uninstall only from the desktop version?

**Comment by moraroy** [comment]
@kafkaus The Uninstall button is in the desktop version. You can install either way desktop or decky it's up to you!

**Comment by kafkaus** [comment]
Thank you very much
