### ISSUE TITLE
Check if manual scan is already in progress

### ISSUE THREAD

**Issue by wnhrt** [moraroy/NonSteamLaunchersDecky#9]
The user should not be able to start multiple manual game checks at the same time via the user interface. I was impatient and pressed the button several times because there was no feedback, resulting in duplicate game entries.

Some feedback, such as a notification or a disabled button, could also be helpful.

Is this possible?

(Otherwise, your script makes a very good first impression. Thank you very much for your work!)

**Comment by moraroy** [comment]
@sysmoon14

**Comment by moraroy** [comment]
@wnhrt fixed!
